Implementaciones/core/urls.py
from django.urls import path
from .views import home
# from .views import HomePageView

urlpatterns = [
    # path('', HomePageView.as_view(), name="home"),
    path('', home, name="home"),
]

Implementaciones/request/urls.py
from django.urls import path
from .views import ImplementationRequestHeaderListView, ImplementationRequestDetailView, UserImplementationRequestHeaderListView, ajax_search
from project.views import GetProjectsJsonList

request_patterns = ([
    path('', ImplementationRequestHeaderListView.as_view(), name='list'),
    path('mis_solicitudes/', UserImplementationRequestHeaderListView.as_view(),
         name='user_request_list'),
    path('mis_solicitudes/listado_projectos/',
         GetProjectsJsonList.as_view(), name='json_project_list'),
    path('mis_solicitudes/nueva_solicitud/',
         ImplementationRequestDetailView.as_view(),
         name="new_implementation_request"
         ),
    path('<int:header_pk>/detalle',
         ImplementationRequestDetailView.as_view(),
         name="detail"
         ),
    path('buscar/',
         ajax_search,
         name="ajax_search"
         ),
], 'request')

Implementaciones/request/models.py
from django.db import models

from core.models import TimeStampedModel
from project.models import Project
from django.contrib.auth.models import User


class ImplementationRequestHeader(TimeStampedModel):
    IMPLEMENTED = 'IM'
    PENDING = 'PN'
    STATES = [
        (IMPLEMENTED, 'Implementado'),
        (PENDING, 'Pendiente'),
    ]
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="implementation_requests",
        blank=False)
    state = models.CharField(
        max_length=2,
        choices=STATES,
        default=PENDING,
    )
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = "solicitud Cabecera"
        verbose_name_plural = "solicitudes Cabeceras"
        ordering = ["-created"]

    def __str__(self):
        return self.project.project_name


class ImplementationRequestDetail(models.Model):
    request_header = models.ForeignKey(
        ImplementationRequestHeader,
        on_delete=models.CASCADE,
        related_name="request_details")
    package = models.CharField(max_length=1000)
    tasks = models.CharField(max_length=1000)
    observations = models.CharField(max_length=500, blank=False)

    class Meta:
        verbose_name = "solicitud Detalle"
        verbose_name_plural = "solicitudes Detalles"
        ordering = ["-package"]

    def __str__(self):
        return self.package

Implementaciones/request/views.py
from django.shortcuts import render
from django.views.generic.list import ListView, View
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.models import User
from django.apps import apps
from django.template.loader import render_to_string
from django.http import JsonResponse

from core.views import email
from .models import ImplementationRequestHeader, ImplementationRequestDetail
from project.models import Project


@method_decorator(login_required, name='dispatch')
class ImplementationRequestHeaderListView(ListView):
    model = ImplementationRequestHeader
    template_name = 'request/request_list.html'
    queryset = ImplementationRequestHeader.objects.all()
    context_object_name = 'requests'
    paginate_by = 10


@method_decorator(staff_member_required, name='dispatch')
class PendingImplementationRequestHeaderListView(ListView):
    model = ImplementationRequestHeader
    template_name = 'request/pending_request_list.html'
    queryset = ImplementationRequestHeader.objects.filter(state='PN').order_by('created')
    context_object_name = 'requests'
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class UserImplementationRequestHeaderListView(ListView):
    model = ImplementationRequestHeader
    template_name = 'request/request_list.html'
    context_object_name = 'requests'
    paginate_by = 10

    def get_queryset(self):
        """Return the current user requests"""
        return ImplementationRequestHeader.objects.filter(
            created_by=self.request.user)


@method_decorator(login_required, name='dispatch')
class ImplementationRequestDetailView(View):
    def get(self, request, header_pk):
        header = get_object_or_404(ImplementationRequestHeader, pk=header_pk)
        details = header.request_details.all()
        data = dict()
        data['details'] = [model_to_dict(detail) for detail in details]
        if not data['details']:
            data['details'] = None
        return JsonResponse(data)

    def post(self, request):
        project_pk = request.POST.get('selectedProjectid', None)
        packages = request.POST.getlist('package', None)
        project_instance = get_object_or_404(Project, pk=project_pk)
        implementation_request_header = ImplementationRequestHeader.objects.create(
            project=project_instance, created_by=request.user)
        for package in packages:
            tasks = request.POST.getlist(package+'task', '-----')
            observations = request.POST.get(package+'observations', '-----')
            tasks_formated = '-----'
            if package[0:5] == '-----':
                package = package[0:5]
            else:
                print(package)
                package = package[:-1]
                if tasks != '-----':
                    tasks_formated = ", ".join(tasks)
                
            ImplementationRequestDetail.objects.create(
                request_header=implementation_request_header,
                package=package,
                tasks=tasks_formated,
                observations=observations)

        # Email Sending
        subject = 'Solicitud Deploy a Produccion del proyecto ' + \
            implementation_request_header.project.project_name
        message = 'El usuario "{}" ha realizado una solicitud de deploy del proyecto "{}". Para mas detalles ingrese a http://implementacionesbi/implementaciones/pendientes/'.format(
            implementation_request_header.created_by, implementation_request_header.project.project_name)
        staff_users = User.objects.filter(is_staff=True)
        email_to = [staff_user.email for staff_user in staff_users]
        email(request, subject, message, email_to)

        return redirect(reverse_lazy('request:user_request_list'))


def ajax_search(request):
    data_dict = {}
    search_parameter = request.GET.get("q")
    path = request.GET.get("path")

    if search_parameter:
        if '/mis_solicitudes/' in path:
            requests = ImplementationRequestHeader.objects.filter(
                created_by=request.user, project__project_name__icontains=search_parameter)
        else:
            requests = ImplementationRequestHeader.objects.filter(
                project__project_name__icontains=search_parameter)
        data_dict["is_requests"] = True
    else:
        requests = search_parameter
        data_dict["is_requests"] = False

    if request.is_ajax():
        html = render_to_string(
            template_name="request/request_search_results.html",
            context={"requests": requests}
        )

        data_dict["html_from_view"] = html
        return JsonResponse(data=data_dict, safe=False)

Implementaciones/request/templates/request/pending_request_list.html
{% extends 'core/base.html' %}
{% load static%}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'request/css/request.css' %}" />
<link rel="stylesheet" href="{% static 'deploy/css/deploy.css' %}" />
{% endblock stylesheet%}

{% block title %}Solicitudes{% endblock %}

{% block content %}
{% include 'deploy/includes/deploy_menu.html' %}
<div class="container bg-white pt-4">
    <div class="row mb-2">
        <div class="col-xl-12">
            <h2>Solicitudes Pendientes</h2>
        </div>

        {% if request.GET.project_name %}
        <div class="col-xl-12">
            <div class="alert alert-success" role="alert">
                Los cambios realizados sobre {{request.GET.project_name}} ya se encuentran en producción.
            </div>
        </div>
        {% endif %}

        <div class="row">
            <div class="col-xl-12">
                <!-- MODAL DEPLOY -->
                <div class="modal fade " id="modalDeploy" tabindex="-1">
                    <div class="modal-dialog modal-sm modal-dialog-centered">
                        <div class="modal-content">

                            <!-- cabecera del diálogo -->
                            <div class="modal-header">
                                <h4 class="modal-title">Implementar</h4>
                                <button type="button" class="close" data-dismiss="modal">X</button>
                            </div>

                            <!-- cuerpo del diálogo -->
                            <div class="modal-body" id="modalBody">
                                <div class="row mb-2">
                                    <div class="container-fluid">
                                        <div class="col-sm-12">
                                            <div class="row">
                                                <div class="col-2">
                                                    <span class="material-icons">
                                                        folder
                                                    </span>
                                                </div>
                                                <div class="col-10">
                                                    <h5 id="requestProject" class="align-middle">
                                                    </h5>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-2">
                                                    <span class="material-icons">
                                                        calendar_today
                                                    </span>
                                                </div>
                                                <div class="col-10">
                                                    <p id="requestDate" class="align-middle">
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-2">
                                                    <span class="material-icons">
                                                        person
                                                    </span>
                                                </div>
                                                <div class="col-10">
                                                    <p id="requestUser" class="align-middle">
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 mb-2">
                                            <form method="POST" id="deployForm" action="implementar/">
                                                {% csrf_token %}
                                                <input type="hidden" id="requestHeader" name="requestHeader" />
                                                <div class="form-row text-center align-middle">
                                                    <div class="col-2">
                                                        <label for="lsn" class="mt-2">LSN:</label>
                                                    </div>
                                                    <div class="col-10">
                                                        <input class="form-control" type="number" id="lsn" name="lsn"
                                                            min="0" max="999999" required/>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                                <!-- pie del diálogo -->
                                <div class="modal-footer" id="modalFooter">
                                    <button class="btn btn-secondary mb-2 btn-cancelar" data-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn btn-primary mb-2" form="deployForm"
                                        id="btnEnviarDeploy">Enviar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-12">
            <table class="table table-hover table-responsive-sm" id="table-requests">
                <thead class="thead-light">
                    <tr>
                        <th class="text-center">Fecha solicitud</th>
                        <th class="text-center">Proyecto</th>
                        <th class="text-center">Detalles</th>
                        <th class="text-center">Solicitante</th>
                        <th class="text-center">Implementar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for request in requests %}
                    <tr>
                        <td class="align-middle text-center">{{request.created|date:'d/m/y H:i'}}</td>
                        <td class="align-middle text-center">{{request.project.project_name}}</td>
                        <td class="text-center align-middle">
                            <a data-toggle="modal" data-target="#modalDetalles" href="" data-id="{{request.id}}"
                                data-url="{% url 'request:detail' request.id %}" onClick="fillDetailsModal(this)">
                                <i class="material-icons align-middle">
                                    list_alt
                                </i>
                            </a>
                        </td>
                        <td class="text-center align-middle">{{request.created_by}}</td>
                        <td class="text-center align-middle" id="deploy-td">
                            <a data-toggle="modal" data-target="#modalDeploy" href="" data-id="{{request.id}}"
                                data-url="{% url 'deploy:deploy_modal' request.id %}" onClick="fillDeployModal(this)">
                                <span class="material-icons deploy-link"></span>
                            </a>
                        </td>
                        {% empty %}
                        <td colspan="5">No hay solicitudes disponibles</td>
                    </tr>
                    {% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-2">
            {% include 'core/includes/pagination.html' %}
        </div>
    </div>


    <!-- MODAL DETALLES SOLICITUD -->
    <div class="modal fade" id="modalDetalles" tabindex="-1">
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">

                <!-- cabecera del diálogo -->
                <!-- <div class="modal-header">
                    <h4 class="modal-title">Detalles</h4>
                    <button type="button" class="close" data-dismiss="modal">X</button>
                </div> -->

                <!-- cuerpo del diálogo -->
                <div class="modal-body">
                    <div class="col-12 mt-2 p-0">
                        <div class="container-fluid px-1">
                            <table class="table table-responsive-sm table-bordered mb-2" id="table-details">
                                <thead class="thead-light">
                                    <tr>
                                        <th class="text-center">Paquete/s</th>
                                        <th class="text-center">Tarea/s</th>
                                        <th class="text-center">Observaciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'request/js/request.js' %}"></script>
<script src="{% static 'deploy/js/deploy.js' %}"></script>
{% endblock javascript%}

Implementaciones/request/templates/request/request_list.html
{% extends 'core/base.html' %}
{% load static%}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'request/css/request.css' %}" />
{% endblock stylesheet%}

{% block title %}Solicitudes{% endblock %}

{% block content %}
{% include 'request/includes/request_menu.html' %}
<div class="container bg-white pt-4">
    <div class="row mb-2 align-middle">
        {% if request.path == "/solicitudes/mis_solicitudes/" %}
        <div class="col-lg-8">
            <h2 class="d-inline">Mis Solicitudes</h2>
            <a href="" class="d-inline" data-toggle="modal" data-target="#modalNuevaSolicitud">
                <span class="material-icons">
                    add_circle
                </span>
            </a>
        </div>
        <div class="col-lg-4">
            <div class="form-row align-items-center">
                <div class="col-sm-12 my-1">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <span class="material-icons" id="search-icon">
                                    search
                                </span>
                            </div>
                        </div>
                        <input type="text" class="form-control" id="search-input"
                            placeholder="Nombre proyecto">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <!-- MODAL SOLICITUD -->
            <div class="modal fade" id="modalNuevaSolicitud" tabindex="-1">
                <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">

                        <!-- cabecera del diálogo -->
                        <!-- <div class="modal-header">
                            <h4 class="modal-title">Nueva Solicitud Implementacion</h4>
                            <button type="button" class="close" data-dismiss="modal">X</button>
                        </div> -->

                        <!-- cuerpo del diálogo -->
                        <div class="modal-body">
                            <form method="POST" id="implementationRequestForm" action="nueva_solicitud/">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-12 mt-2">
                                        <div class="alert alert-danger collapse" role="alert" id="projectAlert">
                                            Debe seleccionar un proyecto.
                                        </div>
                                        <div class="alert alert-danger collapse" role="alert" id="observationAlert">
                                            Debe agregar una descripción sobre los cambios realizados.
                                        </div>
                                        <div class="alert alert-danger collapse" role="alert" id="detailAlert">
                                            No se han agregado detalles a la solicitud.
                                        </div>
                                    </div>
                                    <div class="col-12 mt-2">
                                        <div class="container-fluid">
                                            <div class="row mb-2">
                                                <div class="col-sm-4">
                                                    <label for="projectSelectpicker">Seleccione un proyecto:</label>
                                                    <select class="selectpicker form-control mb-2"
                                                        id="projectSelectpicker" name="projectSelectpicker"
                                                        title="-----" data-live-search="true"
                                                        data-url="{% url 'request:json_project_list' %}">
                                                    </select>
                                                    <input type="hidden" id="selectedProjectid"
                                                        name="selectedProjectid" />
                                                </div>
                                                <div class="col-sm-4">
                                                    <label for="packageSelectpicker">Seleccione un paquete:</label>
                                                    <select class="selectpicker form-control" data-live-search="true"
                                                        id="packageSelectpicker" name="packageSelectpicker"
                                                        title="-----">
                                                    </select>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label for="tasksSelectpicker">Seleccione la/s tarea/s:</label>
                                                    <select class="selectpicker form-control" multiple
                                                        data-live-search="true" id="tasksSelectpicker"
                                                        name="tasksSelectpicker" title="-----">
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="row mb-2">
                                                <div class="col-sm-12 mb-2">
                                                    <label for="observaciones">Ingrese una breve descripcion de los
                                                        cambios
                                                        realizados</label>
                                                    <textarea class="form-control" rows="5" id="observacionesInput"
                                                        name="observaciones" maxlength="500"></textarea>
                                                    <div id="counter" class="pl-1">0/500</div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <button type="button"
                                                        class="btn btn-info add-new form-control">Agregar</button>
                                                </div>
                                                <div class="col-sm-12 mt-4">
                                                    <h5 class="modal-title text-center" id="tituloDetalle">Detalles
                                                        Solicitud</h5>
                                                </div>
                                            </div>

                                            <table class="table table-hover table-responsive-sm" id="table-add">
                                                <thead class="thead-light">
                                                    <tr>
                                                        <th class="text-center">Paquete</th>
                                                        <th class="text-center">Tareas</th>
                                                        <th class="text-center">Observaciones</th>
                                                        <th class="text-center">Editar</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- pie del diálogo -->
                            <div class="modal-footer">
                                <button class="btn btn-secondary mb-2" data-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary mb-2" form="implementationRequestForm"
                                    id="btnEnviar">Enviar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% else %}
        <div class="col-lg-8">
            <h2>Historial Solicitudes</h2>
        </div>
        <div class="col-lg-4">
            <div class="form-row align-items-center">
                <div class="col-sm-12 my-1">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <span class="material-icons" id="search-icon">
                                    search
                                </span>
                            </div>
                        </div>
                        <input type="text" class="form-control" id="search-input"
                            placeholder="Nombre proyecto">
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>


    <table class="table table-hover table-responsive-sm" id="table-requests">
        <thead class="thead-light" style="background-color: #e3f2fd;">
            <tr>
                <th class="text-center">Fecha solicitud</th>
                <th class="text-center">Proyecto</th>
                <th class="text-center">Detalles</th>
                <th class="text-center">Solicitante</th>
                <th class="text-center">Estado</th>
            </tr>
        </thead>
        <tbody id="replaceable-content"></tbody>
        <tbody id="initial-content">
            {% for request in requests %}
            <tr>
                <td class="align-middle text-center">{{request.created|date:'d/m/y H:i'}}</td>
                <td class="text-center align-middle">{{request.project.project_name}}</td>
                <td class="text-center align-middle">
                    <a data-toggle="modal" data-target="#modalDetalles" href="" data-id="{{request.id}}"
                        data-url="{% url 'request:detail' request.id %}" onClick="fillDetailsModal(this)">
                        <i class="material-icons align-middle">
                            list_alt
                        </i>
                    </a>
                </td>
                <td class="text-center align-middle">{{request.created_by}}</td>
                <td class="text-center align-middle">
                    <span class="badge {%if request.state == 'PN' %} badge-danger {% else %} badge-success {%endif%}">
                        {{request.get_state_display}}
                    </span>
                </td>
                {% empty %}
                <td colspan="5">No hay solicitudes disponibles</td>
            </tr>
            {% endfor %}
            </tr>
        </tbody>
    </table>
    <div class="row" id="pagination-row">
        <div class="col-12 mt-2">
            {% include 'core/includes/pagination.html' %}
        </div>
    </div>


    <!-- MODAL DETALLES SOLICITUD -->
    <div class="modal fade" id="modalDetalles" tabindex="-1">
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">

                <!-- cabecera del diálogo -->
                <!-- <div class="modal-header">
                    <h4 class="modal-title">Detalles</h4>
                    <button type="button" class="close" data-dismiss="modal">X</button>
                </div> -->

                <!-- cuerpo del diálogo -->
                <div class="modal-body">

                    <div class="col-12 mt-2 p-0">
                        <div class="container-fluid px-1">
                            <table class="table table-responsive-sm table-bordered mb-2" id="table-details">
                                <thead class="thead-light">
                                    <tr>
                                        <th class="text-center">Paquete/s</th>
                                        <th class="text-center">Tarea/s</th>
                                        <th class="text-center">Observaciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'request/js/request.js' %}"></script>
{% endblock javascript%}

Implementaciones/request/templates/request/request_search_results.html
{% for request in requests %}
<tr>
    <td class="align-middle text-center">{{request.created|date:'d/m/y H:i'}}</td>
    <td class="text-center align-middle">{{request.project.project_name}}</td>
    <td class="text-center align-middle">
        <a data-toggle="modal" data-target="#modalDetalles" href="" data-id="{{request.id}}"
            data-url="{% url 'request:detail' request.id %}" onClick="fillDetailsModal(this)">
            <i class="material-icons align-middle">
                list_alt
            </i>
        </a>
    </td>
    <td class="text-center align-middle">{{request.created_by}}</td>
    <td class="text-center align-middle">
        <span class="badge {%if request.state == 'PN' %} badge-danger {% else %} badge-success {%endif%}">
            {{request.get_state_display}}
        </span>
    </td>
    {% empty %}
    <tr>
    <td colspan="5">No se encontraron resultados</td>
    </tr>
{% endfor %}
</tr>